# Generated by Django 5.2.3 on 2025-06-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
