# Generated by Django 5.2.3 on 2025-07-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_media', '0002_remove_post_image_url_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_username_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
