# Generated by Django 5.2.3 on 2025-07-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_media', '0003_profile_last_username_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
