# Generated by Django 5.2.3 on 2025-07-05 20:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social_media', '0006_commentreply_commentlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentReply',
            new_name='Reply',
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['reply_date'], 'verbose_name_plural': 'Replies'},
        ),
    ]
