# Generated by Django 5.2.3 on 2025-07-15 21:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_media', '0010_alter_comment_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_username_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
